import {
  logo,
  disney,
  microsoft,
  evernote,
  wix,
  shopify,
  paypal,
  invision,
  instagram,
  google,
} from "../assets/images/index";

export const data = [
  {
    id: 1,
    name: "Disney",
    logo: disney,
    description: "Develop",
    members: [evernote, wix],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 2,
    name: "Microsoft",
    logo: microsoft,
    description: "Develop",
    members: [google, shopify, wix],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 3,
    name: "Evernote",
    logo: evernote,
    description: "Develop",
    members: [shopify, google, wix, evernote],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 4,
    name: "Wix",
    logo: wix,
    description: "Develop",
    members: [evernote, shopify, google],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 5,
    name: "Shopify",
    logo: shopify,
    description: "Develop",
    members: [evernote],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 6,
    name: "Paypal",
    logo: paypal,
    description: "Develop",
    members: [instagram],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 7,
    name: "Invision",
    logo: invision,
    description: "Develop",
    members: [evernote],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 8,
    name: "Instagram",
    logo: instagram,
    description: "Develop",
    members: [paypal],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 9,
    name: "Google",
    logo: google,
    description: "Develop",
    members: [evernote],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
  {
    id: 10,
    name: "Evernote",
    logo: evernote,
    description: "Develop",
    members: [shopify],
    categories: "Automation",
    tags: "#DigitalT",
    nextMeeting: "In 30 minutes",
  },
];
